name: Deploy with jsDelivr

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install dependencies and build
        run: |
          pnpm install --no-frozen-lockfile
          pnpm build

      - name: Replace static assets URL
        run: |
          # ----------------------------------------------------
          # 脚本说明
          # 1. 确保你的构建产物位于 'public' 目录
          # 2. 如果你的项目结构或文件名不同，需要修改这个脚本
          # 3. 这个脚本会替换 public/*.html 文件中的链接
          # ----------------------------------------------------

          # 获取仓库名和分支名
          REPO_NAME=$(echo ${{ github.repository }} | cut -d'/' -f2)
          BRANCH_NAME=$(echo ${{ github.ref_name }} | tr '/' '-')

          # 遍历 public 目录下的所有 HTML 文件
          find public -name "*.html" | while read HTML_FILE; do
              CDN_BASE="https://cdn.jsdmirror.com/gh/$REPO_NAME@$BRANCH_NAME"

              sed -i "s#\.\/##g" "$HTML_FILE"
              sed -i "s#href=\"\([^\"]*\)\"#href=\"$CDN_BASE/\1\"#g" "$HTML_FILE"
              sed -i "s#src=\"\([^\"]*\)\"#src=\"$CDN_BASE/\1\"#g" "$HTML_FILE"
              echo "Replaced links in: $HTML_FILE"
          done
      
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './public'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
